# Generated by Django 5.0.4 on 2024-05-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('timeline', models.CharField(max_length=200)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.activity')),
                ('workforce', models.IntegerField(verbose_name='Effectif')),
                ('offered_calls', models.IntegerField(verbose_name='Offered Calls')),
                ('dealed_calls', models.IntegerField(verbose_name='Appels traités')),
                ('total_presence_time', models.IntegerField(verbose_name='Temps de présence/h')),
                ('total_working_time', models.IntegerField(verbose_name='Temps de travail/h')),
                ('total_waiting_time', models.IntegerField(verbose_name="Temps d'attente/h")),
                ('waiting_time_rate', models.IntegerField(verbose_name="Pourcentage d'attente/h")),
                ('total_pausing_time', models.IntegerField(verbose_name='Temps de pause/h')),
                ('pausing_time_rate', models.IntegerField(verbose_name='Pourcentage de pause/h')),
                ('total_production_time', models.IntegerField(verbose_name='Temps de production/h')),
                ('total_calls_per_fte_per_day', models.IntegerField(verbose_name='Calls per FTE per day')),
                ('occupancy_rate', models.IntegerField(verbose_name="Taux d'occupation")),
                ('internal_shrinkage', models.IntegerField(verbose_name='Shrinkage interne')),
                ('a_productivity', models.IntegerField(verbose_name='Productivité')),
                ('paid_hours', models.IntegerField(verbose_name='Heures payées')),
                ('external_shrinkage', models.IntegerField(verbose_name='Shrinkage externe')),
                ('shrinkage', models.IntegerField(verbose_name='Shrinkage')),
                ('b_productivity', models.IntegerField(verbose_name='Productivity')),
                ('sl', models.IntegerField(verbose_name='SL')),
                ('qs', models.IntegerField(verbose_name='QS')),
                ('dma', models.IntegerField(verbose_name='DMA')),
                ('dmc', models.IntegerField()),
                ('dpt', models.IntegerField()),
                ('dmt', models.IntegerField(verbose_name='')),
            ],
        ),
    ]
