# Generated by Django 5.0.4 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='code_call',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='code_file',
        ),
        migrations.AddField(
            model_name='activity',
            name='code_file',
            field=models.ManyToManyField(to='dashboard.codefile'),
        ),
    ]
