# Generated by Django 5.0.4 on 2024-05-10 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LittleFlow',
            fields=[
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.activity')),
                ('dealed_calls', models.IntegerField(verbose_name='Appels traités')),
                ('dma', models.IntegerField(verbose_name='DMA')),
                ('dmc', models.IntegerField(verbose_name='DMC')),
                ('dpt', models.IntegerField(verbose_name='DPT')),
            ],
        ),
        migrations.RemoveField(
            model_name='flow',
            name='timeline',
        ),
        migrations.AddField(
            model_name='flow',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 5, 10), verbose_name='Date fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 10), verbose_name='Date début'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='dmc',
            field=models.IntegerField(verbose_name='DMC'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='dmt',
            field=models.IntegerField(verbose_name='DMT'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='dpt',
            field=models.IntegerField(verbose_name='DPT'),
        ),
    ]
