# Generated by Django 5.0.4 on 2024-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_littleflow_remove_flow_timeline_flow_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='littleflow',
            name='dmt',
            field=models.IntegerField(default=0, verbose_name='DMT'),
            preserve_default=False,
        ),
    ]
