# Generated by Django 5.0.4 on 2024-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_littleflow_dmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='littleflow',
            name='gived_up',
            field=models.IntegerField(default=0, verbose_name='Abandonned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littleflow',
            name='ignored',
            field=models.IntegerField(default=0, verbose_name='Ignored'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littleflow',
            name='ivr',
            field=models.IntegerField(default=0, verbose_name='IVR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littleflow',
            name='offered_calls',
            field=models.IntegerField(default=0, verbose_name='Offered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littleflow',
            name='qs',
            field=models.IntegerField(default=0, verbose_name='QS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littleflow',
            name='sl',
            field=models.IntegerField(default=0, verbose_name='SL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='dealed_calls',
            field=models.IntegerField(verbose_name='Dealed'),
        ),
    ]
