# Generated by Django 5.0.4 on 2024-05-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_littleflow_gived_up_littleflow_ignored_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='littleflow',
            old_name='start_date',
            new_name='process_date',
        ),
        migrations.RemoveField(
            model_name='littleflow',
            name='end_date',
        ),
    ]
