# Generated by Django 5.0.4 on 2024-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_start_date_littleflow_process_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littleflow',
            name='qs',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='QS'),
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='sl',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='SL'),
        ),
    ]
