# Generated by Django 5.0.4 on 2024-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_littleflow_qs_alter_littleflow_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littleflow',
            name='qs',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='QS'),
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='sl',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='SL'),
        ),
    ]
