# Generated by Django 5.0.4 on 2024-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_littleflow_qs_alter_littleflow_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littleflow',
            name='qs',
            field=models.FloatField(verbose_name='QS'),
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='sl',
            field=models.FloatField(verbose_name='SL'),
        ),
    ]
