# Generated by Django 5.0.4 on 2024-05-31 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_littleflow_qs_alter_littleflow_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='littleflow',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity'),
        ),
    ]
