# Generated by Django 5.0.4 on 2024-06-06 14:03

from django.db import migrations, models

from dashboard.models import LittleFlow

def populate_offered(apps, schema_editor):
    lf = apps.get_model('dashboard', 'LittleFlow')
    for obj in lf.objects.all():
        obj.offered_calls = obj.incoming_calls - obj.ivr
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_littleflow_incoming_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='LittleFlow',
            name='offered_calls',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),

        migrations.RunPython(populate_offered),
    ]


