# Generated by Django 5.0.4 on 2024-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20240606_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='littleflow',
            name='sl_dealed_calls',
            field=models.IntegerField(default=0, verbose_name='Dealed in SL'),
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='incoming_calls',
            field=models.IntegerField(verbose_name='Incoming'),
        ),
        migrations.AlterField(
            model_name='littleflow',
            name='offered_calls',
            field=models.IntegerField(verbose_name='Offered'),
        ),
    ]
