# Generated by Django 5.0.4 on 2024-06-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_littleflow_sl_dealed_calls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayKpiDuration',
            fields=[
                ('process_date', models.DateField(verbose_name='Date')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.activity')),
                ('waitDuration', models.IntegerField(verbose_name="Temps d'attente")),
                ('convDuration', models.IntegerField(verbose_name='Temps de communication')),
                ('wrapUpDuration', models.IntegerField(verbose_name='Temps de PostTravail')),
            ],
        ),
    ]
