# Generated by Django 5.0.4 on 2024-06-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_daykpiduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='daykpiduration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daykpiduration',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity'),
        ),
    ]
