# Generated by Django 5.0.4 on 2024-06-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_daykpiduration_id_alter_daykpiduration_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daykpiduration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity'),
        ),
    ]
