# Generated by Django 5.0.4 on 2024-06-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_daykpiduration_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayKpiDuration',
        ),
    ]
