# Generated by Django 5.0.4 on 2024-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_littleflow_convduration_littleflow_waitduration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='littleflow',
            old_name='wrapupDuration',
            new_name='wrapUpDuration',
        ),
    ]
