# Generated by Django 5.0.4 on 2024-06-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_wrapupduration_littleflow_wrapupduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='littleflow',
            old_name='convDuration',
            new_name='conv_duration',
        ),
        migrations.RenameField(
            model_name='littleflow',
            old_name='waitDuration',
            new_name='wait_duration',
        ),
        migrations.RenameField(
            model_name='littleflow',
            old_name='wrapUpDuration',
            new_name='wrapup_duration',
        ),
    ]
