# Generated by Django 5.0.4 on 2024-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_detailedflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(verbose_name='Hour')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn', models.IntegerField(verbose_name='Min')),
            ],
        ),
    ]
