# Generated by Django 5.0.4 on 2024-06-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_detailedhour_detailedmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedflow',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.detailedhour'),
        ),
        migrations.AlterField(
            model_name='detailedflow',
            name='mn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.detailedmin'),
        ),
    ]
