# Generated by Django 5.0.4 on 2024-06-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_rename_hour_detailedhour_hour_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedFlowR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField()),
                ('incoming_calls', models.IntegerField(verbose_name='Incoming')),
                ('offered_calls', models.IntegerField(verbose_name='Offered')),
                ('dealed_calls', models.IntegerField(verbose_name='Dealed')),
                ('dma', models.IntegerField(verbose_name='DMA')),
                ('dmc', models.IntegerField(verbose_name='DMC')),
                ('dmt', models.IntegerField(verbose_name='DMT')),
                ('dpt', models.IntegerField(verbose_name='DPT')),
                ('ivr', models.IntegerField(verbose_name='IVR')),
                ('ignored', models.IntegerField(verbose_name='Ignored')),
                ('gived_up', models.IntegerField(verbose_name='Abandonned')),
                ('qs', models.FloatField(verbose_name='QS')),
                ('sl', models.FloatField(verbose_name='SL')),
                ('sl_dealed_calls', models.IntegerField(default=0, verbose_name='Dealed in SL')),
                ('wait_duration', models.IntegerField(verbose_name='Total Waiting Duration')),
                ('conv_duration', models.IntegerField(verbose_name='Total Conv Duration')),
                ('wrapup_duration', models.IntegerField(verbose_name='Total WrapUp duration')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.activity')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.detailedhour')),
                ('mn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.detailedmin')),
            ],
        ),
    ]
